### ISSUE TITLE
Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by ghost** [qiuqiangkong/sampleRNN_acoustic_scene_generation#5]
After validation, when testing, there is an error : 

```
Traceback (most recent call last):
  File "two_tier_spkdird.py", line 644, in <module>
    test_cost, test_time = monitor(test_feeder)
  File "two_tier_spkdird.py", line 543, in monitor
    _data_feeder = load_data(data_feeder)
  File "two_tier_spkdird.py", line 197, in load_data
    Q_TYPE
  File "/home/vincent/sampleRNN_acoustic_scene_generation/datasets/dataset.py", line 325, in audio_test_feed_epoch
    files_data = numpy.load(data_path)
  File "/home/vincent/miniconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 451, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```
Tested with numpy 1.16.3 and 1.16.4, same result

**Comment by qiuqiangkong** [comment]
The code is based on python 2. Are you using python 3?


Best wishes,


Qiuqiang

________________________________

**Comment by ghost** [comment]
No, I'm using python 2. I suppose I'm using a more recent version of numpy than you, since the default value of "allow_pickle" in numpy.load() has recently been changed from True to False. I have changed the value of the boolean, I will tell you if this solution worked.

**Comment by ghost** [comment]
Nevermind, my file `audio_test.npz` was corrupted ! Sorry for the trouble.
